insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (1, 1, 'For Those About To Rock We Salute You');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (2, 2, 'Balls to the Wall');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (3, 2, 'Restless and Wild');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (4, 1, 'Let There Be Rock');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (5, 3, 'Big Ones');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (6, 4, 'Jagged Little Pill');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (7, 5, 'Facelift');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (8, 6, 'Warner 25 Anos');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (9, 7, 'Plays Metallica By Four Cellos');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (10, 8, 'Audioslave');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (11, 8, 'Out Of Exile');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (12, 9, 'BackBeat Soundtrack');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (13, 10, 'The Best Of Billy Cobham');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (14, 11, 'Alcohol Fueled Brewtality Live! [Disc 1]');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (15, 11, 'Alcohol Fueled Brewtality Live! [Disc 2]');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (16, 12, 'Black Sabbath');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (17, 12, 'Black Sabbath Vol. 4 (Remaster)');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (18, 13, 'Body Count');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (19, 14, 'Chemical Wedding');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (20, 15, 'The Best Of Buddy Guy - The Millenium Collection');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (21, 16, 'Prenda Minha');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (22, 16, 'Sozinho Remix Ao Vivo');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (23, 17, 'Minha Historia');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (24, 18, 'Afrociberdelia');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (25, 18, 'Da Lama Ao Caos');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (26, 19, 'Acústico MTV [Live]');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (27, 19, 'Cidade Negra - Hits');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (28, 20, 'Na Pista');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (29, 21, 'Axé Bahia 2001');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (30, 22, 'BBC Sessions [Disc 1] [Live]');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (31, 23, 'Bongo Fury');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (32, 21, 'Carnaval 2001');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (33, 24, 'Chill: Brazil (Disc 1)');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (34, 6, 'Chill: Brazil (Disc 2)');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (35, 50, 'Garage Inc. (Disc 1)');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (36, 51, 'Greatest Hits II');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (37, 52, 'Greatest Kiss');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (38, 53, 'Heart of the Night');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (39, 54, 'International Superhits');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (40, 55, 'Into The Light');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (41, 56, 'Meus Momentos');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (42, 57, 'Minha História');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (43, 58, 'MK III The Final Concerts [Disc 1]');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (44, 22, 'Physical Graffiti [Disc 1]');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (45, 21, 'Sambas De Enredo 2001');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (46, 59, 'Supernatural');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (47, 37, 'The Best of Ed Motta');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (48, 68, 'The Essential Miles Davis [Disc 1]');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (49, 68, 'The Essential Miles Davis [Disc 2]');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (50, 58, 'The Final Concerts (Disc 2)');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (51, 69, 'Up An'' Atom');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (52, 70, 'Vinícius De Moraes - Sem Limite');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (53, 21, 'Vozes do MPB');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (54, 76, 'Chronicle, Vol. 1');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (55, 76, 'Chronicle, Vol. 2');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (56, 77, 'Cássia Eller - Coleção Sem Limite [Disc 2]');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (57, 77, 'Cássia Eller - Sem Limite [Disc 1]');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (58, 58, 'Come Taste The Band');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (59, 58, 'Deep Purple In Rock');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (60, 58, 'Fireball');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (61, 58, 'Knocking at Your Back Door: The Best Of Deep Purple in the 80''s');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (62, 58, 'Machine Head');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (63, 58, 'Purpendicular');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (64, 58, 'Slaves And Masters');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (65, 58, 'Stormbringer');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (66, 58, 'The Battle Rages On');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (67, 78, 'Vault: Def Leppard''s Greatest Hits');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (68, 79, 'Outbreak');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (69, 80, 'Djavan Ao Vivo - Vol. 02');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (70, 80, 'Djavan Ao Vivo - Vol. 1');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (71, 41, 'Elis Regina-Minha História');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (72, 81, 'The Cream Of Clapton');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (73, 81, 'Unplugged');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (74, 82, 'Album Of The Year');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (75, 82, 'Angel Dust');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (76, 82, 'King For A Day Fool For A Lifetime');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (77, 82, 'The Real Thing');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (78, 83, 'Deixa Entrar');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (79, 84, 'In Your Honor [Disc 1]');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (80, 84, 'In Your Honor [Disc 2]');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (81, 84, 'One By One');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (82, 84, 'The Colour And The Shape');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (83, 85, 'My Way: The Best Of Frank Sinatra [Disc 1]');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (84, 86, 'Roda De Funk');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (85, 27, 'As Canções de Eu Tu Eles');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (86, 27, 'Quanta Gente Veio Ver (Live)');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (87, 27, 'Quanta Gente Veio ver--Bônus De Carnaval');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (88, 87, 'Faceless');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (89, 54, 'American Idiot');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (90, 88, 'Appetite for Destruction');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (91, 88, 'Use Your Illusion I');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (92, 88, 'Use Your Illusion II');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (93, 89, 'Blue Moods');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (94, 90, 'A Matter of Life and Death');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (95, 90, 'A Real Dead One');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (96, 90, 'A Real Live One');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (97, 90, 'Brave New World');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (98, 90, 'Dance Of Death');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (99, 90, 'Fear Of The Dark');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (100, 90, 'Iron Maiden');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (101, 90, 'Killers');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (102, 90, 'Live After Death');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (103, 90, 'Live At Donington 1992 (Disc 1)');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (104, 90, 'Live At Donington 1992 (Disc 2)');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (105, 90, 'No Prayer For The Dying');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (106, 90, 'Piece Of Mind');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (107, 90, 'Powerslave');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (108, 90, 'Rock In Rio [CD1]');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (109, 90, 'Rock In Rio [CD2]');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (110, 90, 'Seventh Son of a Seventh Son');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (111, 90, 'Somewhere in Time');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (112, 90, 'The Number of The Beast');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (113, 90, 'The X Factor');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (114, 90, 'Virtual XI');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (115, 91, 'Sex Machine');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (116, 92, 'Emergency On Planet Earth');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (117, 92, 'Synkronized');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (118, 92, 'The Return Of The Space Cowboy');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (119, 93, 'Get Born');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (120, 94, 'Are You Experienced?');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (121, 95, 'Surfing with the Alien (Remastered)');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (122, 46, 'Jorge Ben Jor 25 Anos');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (123, 96, 'Jota Quest-1995');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (124, 97, 'Cafezinho');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (125, 98, 'Living After Midnight');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (126, 52, 'Unplugged [Live]');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (127, 22, 'BBC Sessions [Disc 2] [Live]');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (128, 22, 'Coda');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (129, 22, 'Houses Of The Holy');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (130, 22, 'In Through The Out Door');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (131, 22, 'IV');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (132, 22, 'Led Zeppelin I');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (133, 22, 'Led Zeppelin II');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (134, 22, 'Led Zeppelin III');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (135, 22, 'Physical Graffiti [Disc 2]');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (136, 22, 'Presence');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (137, 22, 'The Song Remains The Same (Disc 1)');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (138, 22, 'The Song Remains The Same (Disc 2)');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (139, 99, 'A TempestadeTempestade Ou O Livro Dos Dias');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (140, 99, 'Mais Do Mesmo');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (141, 100, 'Greatest Hits');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (142, 101, 'Lulu Santos - RCA 100 Anos De Música - Álbum 01');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (143, 101, 'Lulu Santos - RCA 100 Anos De Música - Álbum 02');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (144, 102, 'Misplaced Childhood');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (145, 103, 'Barulhinho Bom');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (146, 104, 'Seek And Shall Find: More Of The Best (1963-1981)');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (147, 105, 'The Best Of Men At Work');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (148, 50, 'Black Album');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (149, 50, 'Garage Inc. (Disc 2)');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (150, 50, 'Kill ''Em All');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (151, 50, 'Load');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (152, 50, 'Master Of Puppets');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (153, 50, 'ReLoad');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (154, 50, 'Ride The Lightning');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (155, 50, 'St. Anger');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (156, 50, '...And Justice For All');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (157, 68, 'Miles Ahead');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (158, 42, 'Milton Nascimento Ao Vivo');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (159, 42, 'Minas');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (160, 106, 'Ace Of Spades');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (161, 108, 'Demorou...');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (162, 109, 'Motley Crue Greatest Hits');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (163, 110, 'From The Muddy Banks Of The Wishkah [Live]');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (164, 110, 'Nevermind');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (165, 111, 'Compositores');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (166, 112, 'Olodum');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (167, 113, 'Acústico MTV');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (168, 113, 'Arquivo II');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (169, 113, 'Arquivo Os Paralamas Do Sucesso');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (170, 114, 'Bark at the Moon (Remastered)');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (171, 114, 'Blizzard of Ozz');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (172, 114, 'Diary of a Madman (Remastered)');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (173, 114, 'No More Tears (Remastered)');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (174, 114, 'Tribute');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (175, 115, 'Walking Into Clarksdale');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (176, 116, 'Original Soundtracks 1');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (177, 117, 'The Beast Live');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (178, 118, 'Live On Two Legs [Live]');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (179, 118, 'Pearl Jam');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (180, 118, 'Riot Act');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (181, 118, 'Ten');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (182, 118, 'Vs.');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (183, 120, 'Dark Side Of The Moon');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (184, 121, 'Os Cães Ladram Mas A Caravana Não Pára');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (185, 51, 'Greatest Hits I');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (186, 51, 'News Of The World');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (187, 122, 'Out Of Time');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (188, 124, 'Green');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (189, 124, 'New Adventures In Hi-Fi');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (190, 124, 'The Best Of R.E.M.: The IRS Years');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (191, 125, 'Cesta Básica');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (192, 126, 'Raul Seixas');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (193, 127, 'Blood Sugar Sex Magik');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (194, 127, 'By The Way');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (195, 127, 'Californication');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (196, 128, 'Retrospective I (1974-1980)');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (197, 59, 'Santana - As Years Go By');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (198, 59, 'Santana Live');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (199, 130, 'Maquinarama');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (200, 130, 'O Samba Poconé');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (201, 131, 'Judas 0: B-Sides and Rarities');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (202, 131, 'Rotten Apples: Greatest Hits');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (203, 132, 'A-Sides');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (204, 53, 'Morning Dance');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (205, 133, 'In Step');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (206, 134, 'Core');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (207, 135, 'Mezmerize');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (208, 136, '[1997] Black Light Syndrome');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (209, 137, 'Live [Disc 1]');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (210, 137, 'Live [Disc 2]');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (211, 138, 'The Singles');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (212, 139, 'Beyond Good And Evil');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (213, 139, 'Pure Cult: The Best Of The Cult (For Rockers, Ravers, Lovers & Sinners) [UK]');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (214, 140, 'The Doors');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (215, 141, 'The Police Greatest Hits');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (216, 142, 'Hot Rocks, 1964-1971 (Disc 1)');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (217, 142, 'No Security');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (218, 142, 'Voodoo Lounge');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (219, 143, 'Tangents');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (220, 143, 'Transmission');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (221, 144, 'My Generation - The Very Best Of The Who');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (222, 145, 'Serie Sem Limite (Disc 1)');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (223, 145, 'Serie Sem Limite (Disc 2)');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (224, 146, 'Acústico');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (225, 146, 'Volume Dois');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (226, 147, 'Battlestar Galactica: The Story So Far');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (227, 147, 'Battlestar Galactica, Season 3');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (228, 148, 'Heroes, Season 1');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (229, 149, 'Lost, Season 3');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (230, 149, 'Lost, Season 1');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (231, 149, 'Lost, Season 2');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (232, 150, 'Achtung Baby');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (233, 150, 'All That You Can''t Leave Behind');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (234, 150, 'B-Sides 1980-1990');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (235, 150, 'How To Dismantle An Atomic Bomb');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (236, 150, 'Pop');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (237, 150, 'Rattle And Hum');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (238, 150, 'The Best Of 1980-1990');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (239, 150, 'War');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (240, 150, 'Zooropa');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (241, 151, 'UB40 The Best Of - Volume Two [UK]');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (242, 152, 'Diver Down');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (243, 152, 'The Best Of Van Halen, Vol. I');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (244, 152, 'Van Halen');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (245, 152, 'Van Halen III');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (246, 153, 'Contraband');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (247, 72, 'Vinicius De Moraes');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (248, 155, 'Ao Vivo [IMPORT]');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (249, 156, 'The Office, Season 1');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (250, 156, 'The Office, Season 2');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (251, 156, 'The Office, Season 3');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (252, 157, 'Un-Led-Ed');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (253, 158, 'Battlestar Galactica (Classic), Season 1');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (254, 159, 'Aquaman');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (255, 150, 'Instant Karma: The Amnesty International Campaign to Save Darfur');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (256, 114, 'Speak of the Devil');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (257, 179, '20th Century Masters - The Millennium Collection: The Best of Scorpions');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (258, 180, 'House of Pain');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (259, 36, 'Radio Brasil (O Som da Jovem Vanguarda) - Seleccao de Henrique Amaro');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (260, 196, 'Cake: B-Sides and Rarities');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (261, 149, 'LOST, Season 4');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (262, 197, 'Quiet Songs');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (263, 198, 'Muso Ko');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (264, 199, 'Realize');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (265, 200, 'Every Kind of Light');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (266, 201, 'Duos II');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (267, 202, 'Worlds');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (268, 203, 'The Best of Beethoven');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (269, 204, 'Temple of the Dog');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (270, 205, 'Carry On');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (271, 8, 'Revelations');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (272, 206, 'Adorate Deum: Gregorian Chant from the Proper of the Mass');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (273, 207, 'Allegri: Miserere');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (274, 208, 'Pachelbel: Canon & Gigue');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (275, 209, 'Vivaldi: The Four Seasons');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (276, 210, 'Bach: Violin Concertos');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (277, 211, 'Bach: Goldberg Variations');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (278, 212, 'Bach: The Cello Suites');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (279, 213, 'Handel: The Messiah (Highlights)');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (280, 214, 'The World of Classical Favourites');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (281, 215, 'Sir Neville Marriner: A Celebration');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (282, 216, 'Mozart: Wind Concertos');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (283, 217, 'Haydn: Symphonies 99 - 104');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (284, 218, 'Beethoven: Symhonies Nos. 5 & 6');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (285, 219, 'A Soprano Inspired');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (286, 220, 'Great Opera Choruses');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (287, 221, 'Wagner: Favourite Overtures');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (288, 222, 'Fauré: Requiem, Ravel: Pavane & Others');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (289, 223, 'Tchaikovsky: The Nutcracker');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (290, 224, 'The Last Night of the Proms');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (291, 225, 'Puccini: Madama Butterfly - Highlights');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (292, 226, 'Holst: The Planets, Op. 32 & Vaughan Williams: Fantasies');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (293, 227, 'Pavarotti''s Opera Made Easy');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (294, 228, 'Great Performances - Barber''s Adagio and Other Romantic Favorites for Strings');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (295, 229, 'Carmina Burana');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (296, 230, 'A Copland Celebration, Vol. I');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (297, 231, 'Bach: Toccata & Fugue in D Minor');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (298, 232, 'Prokofiev: Symphony No.1');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (299, 233, 'Scheherazade');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (300, 234, 'Bach: The Brandenburg Concertos');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (301, 235, 'Chopin: Piano Concertos Nos. 1 & 2');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (302, 236, 'Mascagni: Cavalleria Rusticana');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (303, 237, 'Sibelius: Finlandia');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (304, 238, 'Beethoven Piano Sonatas: Moonlight & Pastorale');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (305, 240, 'Great Recordings of the Century - Mahler: Das Lied von der Erde');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (306, 241, 'Elgar: Cello Concerto & Vaughan Williams: Fantasias');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (307, 242, 'Adams, John: The Chairman Dances');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (308, 243, 'Tchaikovsky: 1812 Festival Overture, Op.49, Capriccio Italien & Beethoven: Wellington''s Victory');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (309, 244, 'Palestrina: Missa Papae Marcelli & Allegri: Miserere');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (310, 245, 'Prokofiev: Romeo & Juliet');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (311, 226, 'Strauss: Waltzes');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (312, 245, 'Berlioz: Symphonie Fantastique');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (313, 246, 'Bizet: Carmen Highlights');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (314, 247, 'English Renaissance');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (315, 208, 'Handel: Music for the Royal Fireworks (Original Version 1749)');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (316, 248, 'Grieg: Peer Gynt Suites & Sibelius: Pelléas et Mélisande');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (317, 249, 'Mozart Gala: Famous Arias');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (318, 250, 'SCRIABIN: Vers la flamme');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (319, 251, 'Armada: Music from the Courts of England and Spain');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (320, 248, 'Mozart: Symphonies Nos. 40 & 41');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (321, 252, 'Back to Black');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (322, 252, 'Frank');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (323, 253, 'Carried to Dust (Bonus Track Version)');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (324, 254, 'Beethoven: Symphony No. 6 ''Pastoral'' Etc.');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (325, 255, 'Bartok: Violin & Viola Concertos');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (326, 256, 'Mendelssohn: A Midsummer Night''s Dream');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (327, 257, 'Bach: Orchestral Suites Nos. 1 - 4');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (328, 258, 'Charpentier: Divertissements, Airs & Concerts');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (329, 259, 'South American Getaway');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (330, 260, 'Górecki: Symphony No. 3');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (331, 261, 'Purcell: The Fairy Queen');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (332, 262, 'The Ultimate Relexation Album');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (333, 263, 'Purcell: Music for the Queen Mary');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (334, 264, 'Weill: The Seven Deadly Sins');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (335, 265, 'J.S. Bach: Chaconne, Suite in E Minor, Partita in E Major & Prelude, Fugue and Allegro');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (336, 248, 'Prokofiev: Symphony No.5 & Stravinksy: Le Sacre Du Printemps');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (337, 266, 'Szymanowski: Piano Works, Vol. 1');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (338, 267, 'Nielsen: The Six Symphonies');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (339, 268, 'Great Recordings of the Century: Paganini''s 24 Caprices');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (340, 269, 'Liszt - 12 Études D''Execution Transcendante');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (341, 270, 'Great Recordings of the Century - Shubert: Schwanengesang, 4 Lieder');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (342, 271, 'Locatelli: Concertos for Violin, Strings and Continuo, Vol. 3');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (343, 226, 'Respighi:Pines of Rome');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (344, 272, 'Schubert: The Late String Quartets & String Quintet (3 CD''s)');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (345, 273, 'Monteverdi: L''Orfeo');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (346, 274, 'Mozart: Chamber Music');
insert into `albums` (`AlbumId`, `ArtistId`, `Title`) values (347, 275, 'Koyaanisqatsi (Soundtrack from the Motion Picture)');
